# Dockerfile.web
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy only pyproject.toml and poetry.lock first (for caching)
COPY pyproject.toml poetry.lock ./

# Install Poetry itself
RUN pip install --no-cache-dir poetry

# Install dependencies
RUN poetry config virtualenvs.create false
RUN poetry install --no-interaction --no-ansi

# Copy rest of source code
COPY . .

EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "applications.web_server.src.app:app", "--host", "0.0.0.0", "--port", "8000"]
